languageCode = "en-us"
title = "CircuitWall Consultancy"
theme = "landing-page-hugo"

[params]

# You can use Markdown syntax for urls [text](//url.to/source) for
# most longer texts.

# All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
# for more icons. The icons are represented by their corresponding
# CSS class.

# All projects of the portfolio are defined in their own files.
# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
# folder into the 'data' directory at the root of this Hugo site.
# For more informtion take a look at the README.

# To provide some metadata for search engines feel free to add a few
# information about you and your website.
name = "Andrew G. Wu"

# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
description     = "Expertise. Innovation. Success"
subtitle   = "A Java, Spring, JVM performance tuning, bigdata, realtime processing and machine learning consultancy."
buttonText = "Find out more"

# The path must be relative to the static folder
favicon = "favicon.ico"

[[params.social]]
title = "email"
icon = "envelope-o"
url = "mailto:andrew.ge.wu@gmail.com"
[[params.social]]
title = "github"
icon = "github"
url = "https://github.com/CircuitWall"
[[params.social]]
title = "linkedin"
icon = "linkedin"
url = "http://se.linkedin.com/in/andrew-wu-ba92b921"

# Navigation
[params.navigation]
brand = "CircuitWall"

[params.navigation.links]
about     = "About"
services  = "Services"
articles  = "Articles"
portfolio = "Portfolio"
contact   = "Contact"

